// require jquery/jquery.min.js
//= require bootstrap/js/bootstrap.js
//= require bootstrap-select/js/bootstrap-select.js
//= require popper.min.js
//= require jquery-slimscroll/jquery.slimscroll.js
//= require node-waves/waves.js
//= require jquery-countto/jquery.countTo.js
//= require raphael/raphael.min.js
//= require morrisjs/morris.js
//= require chartjs/Chart.bundle.js
//= require flot-charts/jquery.flot.js
//= require flot-charts/jquery.flot.resize.js
//= require flot-charts/jquery.flot.pie.js
//= require flot-charts/jquery.flot.categories.js
//= require flot-charts/jquery.flot.time.js
//= require jquery-sparkline/jquery.sparkline.js
//= require admin.js
//= require pages/index.js
//= require demo.js

