// require plugins/jquery/jquery.min.js
//= require plugins/bootstrap/js/bootstrap.js
//= require plugins/bootstrap-select/js/bootstrap-select.js
//= require popper.min.js
//= require plugins/jquery-slimscroll/jquery.slimscroll.js
//= require plugins/node-waves/waves.js
//= require plugins/jquery-countto/jquery.countTo.js
//= require plugins/raphael/raphael.min.js
//= require plugins/morrisjs/morris.js
//= require plugins/chartjs/Chart.bundle.js
//= require plugins/flot-charts/jquery.flot.js
//= require plugins/flot-charts/jquery.flot.resize.js
//= require plugins/flot-charts/jquery.flot.pie.js
//= require plugins/flot-charts/jquery.flot.categories.js
//= require plugins/flot-charts/jquery.flot.time.js
//= require plugins/jquery-sparkline/jquery.sparkline.js
//= require js/admin.js
//= require js/pages/index.js
//= require js/demo.js

